fint:
  adapter:
    id: unique-id-name
    username:
    password:
    base-url:
    org-id: fintlabs.no
    registration-id: fint
    heartbeat-interval: 1
    capabilities:
      - domain-name: utdanning
        package-name: vurdering
        resource: elevfravar
        fullSyncIntervalInDays: 7
        deltaSyncInterval: IMMEDIATE

spring:
  security:
    oauth2:
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
        registration:
          fint:
            authorization-grant-type: password
            client-id:
            client-secret:
            provider: fint-idp
            scope: fint-adapter